# default false
release_mode = false

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

[app]
name = "Echo boilerplate"
password_hash = "123456789"
jwt_secret = "123456789"

[aws]
s3_bucket_name='echo'
s3_access_key='ASDFKLZXCVJASDf'
s3_secret_key='XXXXimloUoYTgTStTBmVVCfGnqcgLGffpXXXXX'


[server]
graceful = true
addr = ":5000"
protocol = "http"

# Domains
domain= "localhost"
domain_api = "localhost"
domain_web = "loaclhost"
domain_socket = "localhost"

[static]
# BINDATA,FILE(FILE Default)
type = "BINDATA"


[database]
adapter = "postgres"
name = "d60kc96cs2hl2r"
user_name = "ongiczotcjtjwb"
pwd  = "534fbf4395390cf3469a55ca39d7d53b30d65a1a71ec1949a5fca8eaed7aca02"
host = "ec2-54-83-59-120.compute-1.amazonaws.com"
port = 5432

## LOCAL
# adapter = "postgres"
# name = "postgres"
# user_name = "postgres"
# pwd  = "12341234"
# host = "127.0.0.1"

idle_conns = 10
open_conns = 100
log_mode = true

[smtp]
server = "smtp.gmail.com"
port = "587"
from = "noreply@gmail.com"
pwd = "password"

[opentracing]
disable = true
